// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-07-13 20:00:42.67956 +0430 +0430 m=+0.027675278
package git

var (
	Commit  = "3cb4cf8202d70a42c8d352a013c95e29e84b12e7"
	Version = "v0.11.4"
)
