package scylla

/*
   Creation Time: 2019 - Sep - 23
   Created by:  (ehsan)
   Maintainers:
      1.  Ehsan N. Moosa (E2)
   Auditor: Ehsan N. Moosa (E2)
   Copyright Ronak Software Group 2018
*/

// Table & UDT Names
const (
	// Tables
	DbTableAuth              = "auth"
	DbTableClusters          = "clusters"
	DbTableFilesTemp         = "files_temp"
	DbTableDocuments         = "docs"
	DbTableDocumentsCounters = "docs_counters"
	DbTablePhonesUsers       = "phones_users"
	DbTableSystem            = "sys"
	DbTableSystemKeys        = "sys_keys"
	DbTableSystemInstances   = "sys_instances"
	DbTableUsers             = "users"
	DbTableUsersBlocked      = "users_blocked"
	DbTableUsersMessages     = "users_messages"
	DbTableUsersContacts     = "users_contacts"
	DbTableUsersUpdates      = "users_updates"
	DbTableUsersDevices      = "users_devices"
	DbTableUsersDialogs      = "users_dialogs"
	DbTableUsersPeers        = "users_peers"
	DbTableUsersAuth         = "users_auth"
	DbTableUsersDrafts       = "users_drafts"
	DbTableUsersPhotos       = "users_photos"
	DbTableUsersPasswords    = "users_passwords"
	DbTableBotsPeers         = "bots_peers"
	DbTableGroups            = "groups"
	DbTableGroupsPhotos      = "groups_photos"
	DbTableLabels            = "labels"
	DbTableLabelsItems       = "labels_items"

	// Materialized Views
	DbViewAuthByKey              = "auth_by_key"
	DbViewUsersByUsername        = "users_by_username"
	DbViewUsersByPhone           = "users_by_phone"
	DbViewUserMessagesByGlobalID = "users_messages_by_gid"
	DbViewLabelsItemsByMsgID     = "labels_items_by_msgid"
	DbViewLabelsItemsByTime      = "labels_items_by_time"
)

// Column Names
const (
	CnUserID                  = "user_id"
	CnBotID                   = "bot_id"
	CnAuthID                  = "auth_id"
	CnAuthKey                 = "auth_key"
	CnAuthIDs                 = "auth_ids"
	CnGlobalID                = "global_id"
	CnLocalID                 = "local_id"
	CnPeerID                  = "peer_id"
	CnPeerType                = "peer_type"
	CnFName                   = "fname"
	CnLName                   = "lname"
	CnBio                     = "bio"
	CnPhone                   = "phone"
	CnDeviceID                = "device_id"
	CnUsername                = "username"
	CnClientID                = "client_id"
	CnContactID               = "contact_id"
	CnMsgID                   = "msg_id"
	CnCreatedOn               = "created_on"
	CnLastAccess              = "last_access"
	CnEditedOn                = "edited_on"
	CnSenderID                = "sender_id"
	CnSenderMsgID             = "sender_msg_id"
	CnBody                    = "body"
	CnConstructor             = "constructor"
	CnObject                  = "obj"
	CnInbox                   = "inbox"
	CnFwdSenderID             = "fwd_sender_id"
	CnFwdChannelMsgID         = "fwd_channel_msg_id"
	CnFwdChannelID            = "fwd_channel_id"
	CnUpdateID                = "update_id"
	CnKeyType                 = "key_type"
	CnKeyFingerPrint          = "key_finger_print"
	CnRsaKey                  = "rsa_key"
	CnDhPrime                 = "dh_prime"
	CnDhGen                   = "dh_gen"
	CnInstanceID              = "instance_id"
	CnCounterShard            = "counter_shard"
	CnGlobalMsgCounter        = "global_msg_counter"
	CnParamName               = "param_name"
	CnIntValue                = "int_value"
	CnAccessHash              = "access_hash"
	CnMsgAction               = "msg_action"
	CnMsgActionData           = "msg_action_data"
	CnReplyTo                 = "reply_to"
	CnMaxID                   = "max_id"
	CnMinID                   = "min_id"
	CnToken                   = "device_token"
	CnTokenType               = "token_type"
	CnAppVersion              = "app_version"
	CnSystemVersion           = "system_version"
	CnLangCode                = "lang_code"
	CnModel                   = "model"
	CnGroupID                 = "group_id"
	CnTitle                   = "title"
	CnMembers                 = "members"
	CnAdmins                  = "admins"
	CnCreator                 = "creator"
	CnTopMessageID            = "top_msg_id"
	CnTopSenderID             = "top_sender_id"
	CnReadInboxMaxID          = "read_inbox_max_id"
	CnReadOutboxMaxID         = "read_outbox_max_id"
	CnNotifyMuteUntil         = "notify_mute_until"
	CnNotifySound             = "notify_sound"
	CnNotifyFlags             = "notify_flags"
	CnDeactivate              = "deactivate"
	CnAdminEnabled            = "admin_enabled"
	CnDeleted                 = "deleted"
	CnEntities                = "entities"
	CnMentioned               = "mentioned"
	CnScrambled               = "scrambled"
	CnClusterID               = "cluster_id"
	CnFileID                  = "file_id"
	CnDocumentID              = "document_id"
	CnMimeType                = "mime_type"
	CnFileSize                = "file_size"
	CnAttributes              = "attributes"
	CnClusterType             = "type"
	CnClusterAccessKey        = "access_key"
	CnClusterSecretKey        = "secret_key"
	CnClusterSecure           = "secure"
	CnClusterURL              = "url"
	CnClusterLocation         = "location"
	CnMediaType               = "media_type"
	CnMediaData               = "media_data"
	CnContentRead             = "content_read"
	CnPhotoID                 = "photo_id"
	CnPhotoBig                = "photo_big"
	CnPhotoSmall              = "photo_small"
	CnClientIP                = "client_ip"
	CnThumb                   = "thumb"
	CnContactsHash            = "contacts_hash"
	CnPinned                  = "pinned"
	CnDisabled                = "disabled"
	CnPrivacyLastSeen         = "privacy_last_seen"
	CnPrivacyChatInvite       = "privacy_chat_invite"
	CnPrivacyPhone            = "privacy_phone"
	CnPrivacyProfilePhoto     = "privacy_profile_photo"
	CnPrivacyForwardedMessage = "privacy_fwd_msg"
	CnPrivacyCall             = "privacy_call"
	CnMD5Checksum             = "md5_checksum"
	CnRefCount                = "ref_cnt"
	CnEditedID                = "edited_id"
	CnReplyMarkup             = "reply_markup"
	CnReplyMarkupData         = "reply_markup_data"
	CnIsBot                   = "is_bot"
	CnName                    = "name"
	CnColour                  = "colour"
	CnLabelIDs                = "label_ids"
	CnLabelID                 = "label_id"
	CnCount                   = "count"
	CnAlgorithm               = "algo"
	CnAlgorithmData           = "algo_data"
	CnHint                    = "hint"
	CnSrpHash                 = "srp_hash"
	CnSecurityQuestions       = "security_questions"
	CnBlockedUsers            = "blocked_users"
)
