// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: imsg.proto

package rony

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RaftState int32

const (
	RaftState_None      RaftState = 0
	RaftState_Follower  RaftState = 1
	RaftState_Candidate RaftState = 2
	RaftState_Leader    RaftState = 3
	RaftState_Shutdown  RaftState = 4
)

// Enum value maps for RaftState.
var (
	RaftState_name = map[int32]string{
		0: "None",
		1: "Follower",
		2: "Candidate",
		3: "Leader",
		4: "Shutdown",
	}
	RaftState_value = map[string]int32{
		"None":      0,
		"Follower":  1,
		"Candidate": 2,
		"Leader":    3,
		"Shutdown":  4,
	}
)

func (x RaftState) Enum() *RaftState {
	p := new(RaftState)
	*p = x
	return p
}

func (x RaftState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftState) Descriptor() protoreflect.EnumDescriptor {
	return file_imsg_proto_enumTypes[0].Descriptor()
}

func (RaftState) Type() protoreflect.EnumType {
	return &file_imsg_proto_enumTypes[0]
}

func (x RaftState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftState.Descriptor instead.
func (RaftState) EnumDescriptor() ([]byte, []int) {
	return file_imsg_proto_rawDescGZIP(), []int{0}
}

// ClusterMessage
type ClusterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   []byte           `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Store    []*KeyValue      `protobuf:"bytes,2,rep,name=Store,proto3" json:"Store,omitempty"`
	Envelope *MessageEnvelope `protobuf:"bytes,3,opt,name=Envelope,proto3" json:"Envelope,omitempty"`
}

func (x *ClusterMessage) Reset() {
	*x = ClusterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage) ProtoMessage() {}

func (x *ClusterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_imsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage.ProtoReflect.Descriptor instead.
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return file_imsg_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMessage) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ClusterMessage) GetStore() []*KeyValue {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *ClusterMessage) GetEnvelope() *MessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// RaftCommand
type RaftCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   []byte           `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Store    []*KeyValue      `protobuf:"bytes,2,rep,name=Store,proto3" json:"Store,omitempty"`
	Envelope *MessageEnvelope `protobuf:"bytes,3,opt,name=Envelope,proto3" json:"Envelope,omitempty"`
}

func (x *RaftCommand) Reset() {
	*x = RaftCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCommand) ProtoMessage() {}

func (x *RaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_imsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCommand.ProtoReflect.Descriptor instead.
func (*RaftCommand) Descriptor() ([]byte, []int) {
	return file_imsg_proto_rawDescGZIP(), []int{1}
}

func (x *RaftCommand) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *RaftCommand) GetStore() []*KeyValue {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *RaftCommand) GetEnvelope() *MessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// EdgeNode
type EdgeNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID      []byte    `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	ReplicaSet    uint64    `protobuf:"varint,2,opt,name=ReplicaSet,proto3" json:"ReplicaSet,omitempty"`
	ShardRangeMin uint32    `protobuf:"varint,3,opt,name=ShardRangeMin,proto3" json:"ShardRangeMin,omitempty"`
	ShardRangeMax uint32    `protobuf:"varint,4,opt,name=ShardRangeMax,proto3" json:"ShardRangeMax,omitempty"`
	RaftPort      uint32    `protobuf:"varint,5,opt,name=RaftPort,proto3" json:"RaftPort,omitempty"`
	RaftState     RaftState `protobuf:"varint,6,opt,name=RaftState,proto3,enum=rony.RaftState" json:"RaftState,omitempty"`
	GatewayAddr   []string  `protobuf:"bytes,7,rep,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
}

func (x *EdgeNode) Reset() {
	*x = EdgeNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeNode) ProtoMessage() {}

func (x *EdgeNode) ProtoReflect() protoreflect.Message {
	mi := &file_imsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeNode.ProtoReflect.Descriptor instead.
func (*EdgeNode) Descriptor() ([]byte, []int) {
	return file_imsg_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeNode) GetServerID() []byte {
	if x != nil {
		return x.ServerID
	}
	return nil
}

func (x *EdgeNode) GetReplicaSet() uint64 {
	if x != nil {
		return x.ReplicaSet
	}
	return 0
}

func (x *EdgeNode) GetShardRangeMin() uint32 {
	if x != nil {
		return x.ShardRangeMin
	}
	return 0
}

func (x *EdgeNode) GetShardRangeMax() uint32 {
	if x != nil {
		return x.ShardRangeMax
	}
	return 0
}

func (x *EdgeNode) GetRaftPort() uint32 {
	if x != nil {
		return x.RaftPort
	}
	return 0
}

func (x *EdgeNode) GetRaftState() RaftState {
	if x != nil {
		return x.RaftState
	}
	return RaftState_None
}

func (x *EdgeNode) GetGatewayAddr() []string {
	if x != nil {
		return x.GatewayAddr
	}
	return nil
}

var File_imsg_proto protoreflect.FileDescriptor

var file_imsg_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x6f,
	0x6e, 0x79, 0x1a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01,
	0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x6e, 0x79, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x72, 0x6f, 0x6e, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x22, 0x7e, 0x0a, 0x0b, 0x52, 0x61, 0x66, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x6e, 0x79, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x72, 0x6f, 0x6e, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x22, 0xff, 0x01, 0x0a, 0x08, 0x45, 0x64, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e,
	0x12, 0x24, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x61, 0x66, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x52, 0x61, 0x66, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x52, 0x61, 0x66, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x72, 0x6f, 0x6e, 0x79, 0x2e, 0x52, 0x61, 0x66,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x52, 0x61, 0x66, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x2a, 0x4c, 0x0a, 0x09, 0x52, 0x61, 0x66, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x10,
	0x04, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x72, 0x6f, 0x6e, 0x61, 0x6b, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x72, 0x6f, 0x6e, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imsg_proto_rawDescOnce sync.Once
	file_imsg_proto_rawDescData = file_imsg_proto_rawDesc
)

func file_imsg_proto_rawDescGZIP() []byte {
	file_imsg_proto_rawDescOnce.Do(func() {
		file_imsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_imsg_proto_rawDescData)
	})
	return file_imsg_proto_rawDescData
}

var file_imsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_imsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_imsg_proto_goTypes = []interface{}{
	(RaftState)(0),          // 0: rony.RaftState
	(*ClusterMessage)(nil),  // 1: rony.ClusterMessage
	(*RaftCommand)(nil),     // 2: rony.RaftCommand
	(*EdgeNode)(nil),        // 3: rony.EdgeNode
	(*KeyValue)(nil),        // 4: rony.KeyValue
	(*MessageEnvelope)(nil), // 5: rony.MessageEnvelope
}
var file_imsg_proto_depIdxs = []int32{
	4, // 0: rony.ClusterMessage.Store:type_name -> rony.KeyValue
	5, // 1: rony.ClusterMessage.Envelope:type_name -> rony.MessageEnvelope
	4, // 2: rony.RaftCommand.Store:type_name -> rony.KeyValue
	5, // 3: rony.RaftCommand.Envelope:type_name -> rony.MessageEnvelope
	0, // 4: rony.EdgeNode.RaftState:type_name -> rony.RaftState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_imsg_proto_init() }
func file_imsg_proto_init() {
	if File_imsg_proto != nil {
		return
	}
	file_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_imsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imsg_proto_goTypes,
		DependencyIndexes: file_imsg_proto_depIdxs,
		EnumInfos:         file_imsg_proto_enumTypes,
		MessageInfos:      file_imsg_proto_msgTypes,
	}.Build()
	File_imsg_proto = out.File
	file_imsg_proto_rawDesc = nil
	file_imsg_proto_goTypes = nil
	file_imsg_proto_depIdxs = nil
}
