// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: node.proto

package rony

import (
	fmt "fmt"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RaftState int32

const (
	RaftState_None      RaftState = 0
	RaftState_Follower  RaftState = 1
	RaftState_Candidate RaftState = 2
	RaftState_Leader    RaftState = 3
	RaftState_Shutdown  RaftState = 4
)

var RaftState_name = map[int32]string{
	0: "None",
	1: "Follower",
	2: "Candidate",
	3: "Leader",
	4: "Shutdown",
}

var RaftState_value = map[string]int32{
	"None":      0,
	"Follower":  1,
	"Candidate": 2,
	"Leader":    3,
	"Shutdown":  4,
}

func (x RaftState) Enum() *RaftState {
	p := new(RaftState)
	*p = x
	return p
}

func (x RaftState) String() string {
	return proto.EnumName(RaftState_name, int32(x))
}

func (x *RaftState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RaftState_value, data, "RaftState")
	if err != nil {
		return err
	}
	*x = RaftState(value)
	return nil
}

func (RaftState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

// edgeNode
type EdgeNode struct {
	ServerID    string    `protobuf:"bytes,1,req,name=ServerID" json:"ServerID"`
	ReplicaSet  uint32    `protobuf:"varint,2,opt,name=ReplicaSet" json:"ReplicaSet"`
	ShardSet    uint32    `protobuf:"varint,3,opt,name=ShardSet" json:"ShardSet"`
	RaftPort    uint32    `protobuf:"varint,4,opt,name=RaftPort" json:"RaftPort"`
	ShardMin    uint32    `protobuf:"varint,5,opt,name=ShardMin" json:"ShardMin"`
	ShardMax    uint32    `protobuf:"varint,6,opt,name=ShardMax" json:"ShardMax"`
	GatewayAddr string    `protobuf:"bytes,7,req,name=GatewayAddr" json:"GatewayAddr"`
	RaftState   RaftState `protobuf:"varint,8,opt,name=RaftState,enum=rony.RaftState" json:"RaftState"`
}

func (m *EdgeNode) Reset()         { *m = EdgeNode{} }
func (m *EdgeNode) String() string { return proto.CompactTextString(m) }
func (*EdgeNode) ProtoMessage()    {}
func (*EdgeNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}
func (m *EdgeNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EdgeNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EdgeNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EdgeNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeNode.Merge(m, src)
}
func (m *EdgeNode) XXX_Size() int {
	return m.Size()
}
func (m *EdgeNode) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeNode.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeNode proto.InternalMessageInfo

func (m *EdgeNode) GetServerID() string {
	if m != nil {
		return m.ServerID
	}
	return ""
}

func (m *EdgeNode) GetReplicaSet() uint32 {
	if m != nil {
		return m.ReplicaSet
	}
	return 0
}

func (m *EdgeNode) GetShardSet() uint32 {
	if m != nil {
		return m.ShardSet
	}
	return 0
}

func (m *EdgeNode) GetRaftPort() uint32 {
	if m != nil {
		return m.RaftPort
	}
	return 0
}

func (m *EdgeNode) GetShardMin() uint32 {
	if m != nil {
		return m.ShardMin
	}
	return 0
}

func (m *EdgeNode) GetShardMax() uint32 {
	if m != nil {
		return m.ShardMax
	}
	return 0
}

func (m *EdgeNode) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

func (m *EdgeNode) GetRaftState() RaftState {
	if m != nil {
		return m.RaftState
	}
	return RaftState_None
}

func init() {
	proto.RegisterEnum("rony.RaftState", RaftState_name, RaftState_value)
	proto.RegisterType((*EdgeNode)(nil), "rony.edgeNode")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd0, 0xd1, 0x4a, 0xf3, 0x30,
	0x14, 0xc0, 0xf1, 0xa6, 0xeb, 0xb7, 0xaf, 0x3d, 0x3a, 0x2d, 0xb9, 0xca, 0x55, 0x2c, 0x22, 0x52,
	0xbc, 0xe8, 0x85, 0x3e, 0x81, 0x53, 0x14, 0x61, 0x1b, 0xd2, 0x3e, 0x41, 0x30, 0x47, 0x57, 0x28,
	0xc9, 0x08, 0xd1, 0x6e, 0x6f, 0xe1, 0xdb, 0xf8, 0x0a, 0xbb, 0xdc, 0xa5, 0x57, 0x22, 0xed, 0x8b,
	0x48, 0x65, 0x76, 0x81, 0xdd, 0xfe, 0xf3, 0x3b, 0x27, 0x24, 0x00, 0x4a, 0x4b, 0xcc, 0x16, 0x46,
	0x5b, 0x4d, 0x03, 0xa3, 0xd5, 0xea, 0xf4, 0xc3, 0x87, 0x10, 0xe5, 0x0b, 0xce, 0xb4, 0x44, 0x9a,
	0x40, 0x58, 0xa0, 0x79, 0x43, 0xf3, 0x70, 0xcb, 0x48, 0xe2, 0xa7, 0xd1, 0x38, 0x58, 0x7f, 0x9d,
	0x78, 0x79, 0x5f, 0xe9, 0x19, 0x40, 0x8e, 0x8b, 0xaa, 0x7c, 0x12, 0x05, 0x5a, 0xe6, 0x27, 0x24,
	0x1d, 0x6d, 0x8d, 0xd3, 0x7f, 0xf7, 0xcc, 0x85, 0x91, 0x9d, 0x19, 0x38, 0xa6, 0xaf, 0x9d, 0xc8,
	0xc5, 0xb3, 0x7d, 0xd4, 0xc6, 0xb2, 0xc0, 0x15, 0x7f, 0xb5, 0xdf, 0x31, 0x2d, 0x15, 0xfb, 0xb7,
	0xb7, 0x63, 0x5a, 0xaa, 0x9d, 0x10, 0x4b, 0x36, 0xdc, 0x17, 0x62, 0x49, 0xcf, 0xe1, 0xe0, 0x5e,
	0x58, 0xac, 0xc5, 0xea, 0x5a, 0x4a, 0xc3, 0xfe, 0x3b, 0x4f, 0x72, 0x0f, 0xe8, 0x15, 0x44, 0xdd,
	0xbd, 0x85, 0x15, 0x16, 0x59, 0x98, 0x90, 0xf4, 0xe8, 0xf2, 0x38, 0xeb, 0xbe, 0x27, 0xeb, 0xf3,
	0x76, 0x6c, 0xe7, 0x2e, 0x26, 0xce, 0x10, 0x0d, 0x21, 0x98, 0x69, 0x85, 0xb1, 0x47, 0x0f, 0x21,
	0xbc, 0xd3, 0x55, 0xa5, 0x6b, 0x34, 0x31, 0xa1, 0x23, 0x88, 0x6e, 0x84, 0x92, 0xa5, 0x14, 0x16,
	0x63, 0x9f, 0x02, 0x0c, 0x27, 0x28, 0x24, 0x9a, 0x78, 0xd0, 0xc1, 0x62, 0xfe, 0x6a, 0xa5, 0xae,
	0x55, 0x1c, 0x8c, 0xd9, 0xba, 0xe1, 0x64, 0xd3, 0x70, 0xf2, 0xdd, 0x70, 0xf2, 0xde, 0x72, 0x6f,
	0xd3, 0x72, 0xef, 0xb3, 0xe5, 0xde, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x8e, 0x3f, 0x9f,
	0xb4, 0x01, 0x00, 0x00,
}

func (m *EdgeNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EdgeNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EdgeNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintNode(dAtA, i, uint64(m.RaftState))
	i--
	dAtA[i] = 0x40
	i -= len(m.GatewayAddr)
	copy(dAtA[i:], m.GatewayAddr)
	i = encodeVarintNode(dAtA, i, uint64(len(m.GatewayAddr)))
	i--
	dAtA[i] = 0x3a
	i = encodeVarintNode(dAtA, i, uint64(m.ShardMax))
	i--
	dAtA[i] = 0x30
	i = encodeVarintNode(dAtA, i, uint64(m.ShardMin))
	i--
	dAtA[i] = 0x28
	i = encodeVarintNode(dAtA, i, uint64(m.RaftPort))
	i--
	dAtA[i] = 0x20
	i = encodeVarintNode(dAtA, i, uint64(m.ShardSet))
	i--
	dAtA[i] = 0x18
	i = encodeVarintNode(dAtA, i, uint64(m.ReplicaSet))
	i--
	dAtA[i] = 0x10
	i -= len(m.ServerID)
	copy(dAtA[i:], m.ServerID)
	i = encodeVarintNode(dAtA, i, uint64(len(m.ServerID)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintNode(dAtA []byte, offset int, v uint64) int {
	offset -= sovNode(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EdgeNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServerID)
	n += 1 + l + sovNode(uint64(l))
	n += 1 + sovNode(uint64(m.ReplicaSet))
	n += 1 + sovNode(uint64(m.ShardSet))
	n += 1 + sovNode(uint64(m.RaftPort))
	n += 1 + sovNode(uint64(m.ShardMin))
	n += 1 + sovNode(uint64(m.ShardMax))
	l = len(m.GatewayAddr)
	n += 1 + l + sovNode(uint64(l))
	n += 1 + sovNode(uint64(m.RaftState))
	return n
}

func sovNode(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNode(x uint64) (n int) {
	return sovNode(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EdgeNode) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNode
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: edgeNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: edgeNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicaSet", wireType)
			}
			m.ReplicaSet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplicaSet |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardSet", wireType)
			}
			m.ShardSet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardSet |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftPort", wireType)
			}
			m.RaftPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftPort |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardMin", wireType)
			}
			m.ShardMin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardMin |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardMax", wireType)
			}
			m.ShardMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardMax |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftState", wireType)
			}
			m.RaftState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftState |= RaftState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNode(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNode
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNode
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ServerID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("GatewayAddr")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNode(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNode
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNode
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNode
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNode
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNode        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNode          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNode = fmt.Errorf("proto: unexpected end of group")
)
