// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-07-14 15:07:03.206899 +0430 +0430 m=+0.030453527
package codegen

var (
	Commit  = "588a0f8a5ac885b4d6926213e956c8b2017d37df"
	Version = "v0.11.4"
)
