// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-07-26 11:23:01.142328 +0430 +0430 m=+0.031417249
package codegen

var (
	Commit  = "0751ac02eba24266dfe29ba3b08eaee49bde22d4"
	Version = "v0.12.18"
)
