// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-07-15 09:53:07.376911 +0430 +0430 m=+0.029218771
package codegen

var (
	Commit  = "09c4713965ad41e7be936344e5aa68cbe49a9fa7"
	Version = "v0.12.0"
)
