package main

import (
	"fmt"
	"github.com/ronaksoft/rony"
	"github.com/ronaksoft/rony/cmd/protoc-gen-gorony/aggregate"
	"github.com/ronaksoft/rony/cmd/protoc-gen-gorony/singleton"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"strings"
)

func main() {
	plugins := make(map[string]struct{})
	pgo := protogen.Options{
		ParamFunc: func(name, value string) error {
			switch name {
			case "plugin":
				for _, p := range strings.Split(value, "|") {
					plugins[p] = struct{}{}
				}
			}
			return nil
		},
		ImportRewriteFunc: func(path protogen.GoImportPath) protogen.GoImportPath {
			// TODO:: this is a hack for bug in Golang/Protobuf which does not support go module versions
			switch path {
			case "github.com/scylladb/gocqlx":
				return "github.com/scylladb/gocqlx/v2"
			}
			return path
		},
	}
	pgo.Run(func(plugin *protogen.Plugin) error {
		for _, f := range plugin.Files {
			if !f.Generate || f.Proto.GetPackage() == "google.protobuf" {
				continue
			}

			// Create the generator func
			g := plugin.NewGeneratedFile(fmt.Sprintf("%s.rony.go", f.GeneratedFilenamePrefix), f.GoImportPath)
			g.P("// Code generated by Rony's protoc plugin; DO NOT EDIT.")
			g.P()

			// Generate all the helper functions
			GenHelpers(f, g)

			// Generate Aggregate or Singleton repo functionality based on the 'rony_repo' option
			g1 := aggregate.New(f, g)
			g1.Generate()

			g2 := singleton.New(f, g)
			g2.Generate()

			// Generate RPCs if there is any service definition in the file
			if len(f.Services) > 0 {
				g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "github.com/ronaksoft/rony/edge"})
				g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "google.golang.org/protobuf/proto"})
				g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "fmt"})
				if f.GoPackageName != "rony" {
					g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "github.com/ronaksoft/rony"})
				}

				for _, s := range f.Services {
					GenRPC(f, s, g)
					opt, _ := s.Desc.Options().(*descriptorpb.ServiceOptions)
					if proto.GetExtension(opt, rony.E_RonyCobraCmd).(bool) {
						g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "github.com/spf13/cobra"})
						g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "github.com/ronaksoft/rony/config"})
						// g.QualifiedGoIdent(protogen.GoIdent{GoName: "", GoImportPath: "time"})
						GenCobraCmd(f, s, g)
					}
				}

			}

		}
		return nil
	})
	return
}
