version: '2'
services:

  # ScyllaDb Database
  scylla:
    restart: always
    image: scylladb/scylla:4.4.3
    container_name: scylladb
    volumes:
      - ./_hdd/db-main/:/var/lib/scylla
    networks:
      - rony-net
    ports:
      - 9042:9042


networks:
  rony-net:
    external:
      name: rony-net
